# Generated by Django 5.2.17 on 2026-09-28 04:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizzes', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('QUICK', 'Quick'), ('QUIZ', 'Quiz')], max_length=5)),
                ('mode', models.CharField(choices=[('TEACHER_PACED', 'Teacher Paced'), ('STUDENT_PACED', 'Student Paced')], default='TEACHER_PACED', max_length=13)),
                ('quiz_title', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('LIVE', 'Live'), ('ENDED', 'Ended')], default='LIVE', max_length=5)),
                ('current_index', models.PositiveIntegerField(default=0)),
                ('show_feedback', models.BooleanField(default=False)),
                ('shuffle_questions', models.BooleanField(default=False)),
                ('hide_results', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='rooms.room')),
                ('source_quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='quizzes.quiz')),
            ],
            options={
                'verbose_name_plural': 'activities',
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ActivityQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('MC', 'Mc'), ('TF', 'Tf'), ('SA', 'Sa')], max_length=2)),
                ('prompt', models.TextField(blank=True)),
                ('explanation', models.TextField(blank=True)),
                ('choices', models.JSONField(blank=True, default=list)),
                ('correct_index', models.PositiveIntegerField(blank=True, null=True)),
                ('accepted_answers', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='activities.activity')),
            ],
            options={
                'ordering': ['activity', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('question_order', models.JSONField(blank=True, null=True)),
                ('is_removed', models.BooleanField(default=False)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='activities.activity')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_index', models.PositiveIntegerField(blank=True, null=True)),
                ('text_answer', models.CharField(blank=True, max_length=500)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='activities.participant')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='activities.activityquestion')),
            ],
            options={
                'ordering': ['submitted_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'LIVE')), fields=('room',), name='one_live_activity_per_room'),
        ),
        migrations.AddConstraint(
            model_name='activityquestion',
            constraint=models.UniqueConstraint(fields=('activity', 'order'), name='activity_question_order_unique'),
        ),
        migrations.AddConstraint(
            model_name='response',
            constraint=models.UniqueConstraint(fields=('participant', 'question'), name='one_response_per_participant_question'),
        ),
    ]
