# Generated by Django 5.2.17 on 2026-09-28 03:23

from django.conf import settings
from django.db import migrations


def create_missing_profiles(apps, schema_editor):
    # Users that existed before email verification get an unverified profile; verify
    # them with `manage.py verify_teacher <email>`.
    User = apps.get_model(*settings.AUTH_USER_MODEL.split("."))
    TeacherProfile = apps.get_model("accounts", "TeacherProfile")
    TeacherProfile.objects.bulk_create(
        [TeacherProfile(user_id=pk) for pk in User.objects.filter(profile__isnull=True).values_list("pk", flat=True)]
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_teacher_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(create_missing_profiles, migrations.RunPython.noop),
    ]
