# Generated by Django 5.2.17 on 2026-09-28 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('MC', 'Mc'), ('TF', 'Tf'), ('SA', 'Sa')], max_length=2)),
                ('prompt', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('choices', models.JSONField(blank=True, default=list)),
                ('correct_index', models.PositiveIntegerField(blank=True, null=True)),
                ('accepted_answers', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.quiz')),
            ],
            options={
                'ordering': ['quiz', 'order'],
                'constraints': [models.UniqueConstraint(fields=('quiz', 'order'), name='quiz_question_order_unique')],
            },
        ),
    ]
